final products = [
  {
    'id': '0',
    'title': 'Air Jordan 1 High G ',
    'Price': 18395.00,
    'imageURL': 'assets/images/shoes_1.png',
    'Company': 'Nike',
    'Size': [9, 10, 11, 12],
  },
  {
    'id': '0',
    'title': 'Air Jordan 7 Retro',
    'Price': 15099.00,
    'imageURL': 'assets/images/shoes_2.png',
    'Company': 'Nike',
    'Size': [9, 10, 11, 12],
  },
  {
    'id': '0',
    'title': 'AIR JORDAN 1 MID BLACK FIRE ',
    'Price': 17294.58,
    'imageURL': 'assets/images/shoes_3.png',
    'Company': 'Nike',
    'Size': [9, 10, 11, 12],
  },
  {
    'id': '0',
    'title': 'JORDAN 1 MID SHADOW (W)',
    'Price': 25990.00,
    'imageURL': 'assets/images/shoes_4.png',
    'Company': 'Nike',
    'Size': [9, 10, 11, 12],
  },
  {
    'id': '0',
    'title': 'Air Jordan 1 Retro High',
    'Price': 17990.00,
    'imageURL': 'assets/images/shoes_5.png',
    'Company': 'Nike',
    'Size': [9, 10, 11, 12],
  },
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'Price': 1599.1,
    'imageURL': 'assets/images/shoes_6.png',
    'Company': 'Nike',
    'Size': [9, 10, 11, 12],
  },
  
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'Price': 1599.1,
    'imageURL': 'assets/images/shoes_8.png',
    'Company': 'Nike',
    'Size': [9, 10, 11, 12],
  },
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'Price': 1599.1,
    'imageURL': 'assets/images/shoes_9.png',
    'Company': 'Nike',
    'Size': [9, 10, 11, 12],
  },
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'Price': 1599.1,
    'imageURL': 'assets/images/shoes_10.png',
    'Company': 'Nike',
    'Size': [9, 10, 11, 12],
  },
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'Price': 1599.1,
    'imageURL': 'assets/images/shoes_11.png',
    'Company': 'Nike',
    'Size': [9, 10, 11, 12],
  },
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'Price': 1599.1,
    'imageURL': 'assets/images/shoes_12.png',
    'Company': 'Nike',
    'Size': [9, 10, 11, 12],
  },
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'Price': 1599.1,
    'imageURL': 'assets/images/shoes_13.png',
    'Company': 'Nike',
    'Size': [9, 10, 11, 12],
  },
];
